kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: consul
  name: consul-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-pv0
  labels:
    type: local
  namespace: consul
spec:
  storageClassName: consul-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/consul/data"
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-pv1
  labels:
    type: local
  namespace: consul
spec:
  storageClassName: consul-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/consul/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-pv2
  labels:
    type: local
  namespace: consul
spec:
  storageClassName: consul-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/consul/data"
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  labels:
    app: consul 
  name: data-consul-consul-server-0
  namespace: consul
spec:
  storageClassName: consul-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  labels:
    app: consul 
  name: data-consul-consul-server-1
  namespace: consul
spec:
  storageClassName: consul-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  labels:
    app: consul 
  name: data-consul-consul-server-2
  namespace: consul
spec:
  storageClassName: consul-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi