apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-pv0
  labels:
    type: local
spec:
  storageClassName: consul-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/consul/data"
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-pv1
  labels:
    type: local
spec:
  storageClassName: consul-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/consul/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-consul-pv2
  labels:
    type: local
spec:
  storageClassName: consul-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/consul/data"

