apiVersion: v1
kind: ServiceAccount
metadata:
  name: movieservice
---
apiVersion: v1
kind: Service
metadata:
  name: movieservice
spec:
  selector:
    app: movieservice
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movieservice
  name: movieservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movieservice
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'mysql:3306'
      labels:
        app: movieservice
    spec:
      containers:
      - name: movieservice
        image: jakobschlager/movieservice:release
        ports:
        - containerPort: 5000
